server:
  port: 80
spring:
  datasource:
    dynamic:
      datasource:
        master:
          driver-class-name: com.mysql.jdbc.Driver
          password: security
          url: jdbc:mysql://127.0.0.1:3306/security?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
          username: security
        slave_1:
          driver-class-name: com.mysql.jdbc.Driver
          password: security2
          url: jdbc:mysql://127.0.0.1:3306/security2?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
          username: security2
        slave_2:
          driver-class-name: com.mysql.jdbc.Driver
          password: security3
          url: jdbc:mysql://127.0.0.1:3306/security3?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
          username: security3
      primary: master
      strict: false
swagger:
  enable: false
